/**
 * Portfolio Content & Configuration Data
 * Tailored for Masood Haider — CS Student & Full Stack Developer
 */

export const portfolioData = {
  profile: {
    name: 'Masood Haider',
    title: 'Computer Science Student & Full Stack Developer',
    email: 'masoodhaider.dev@gmail.com',
    location: 'Remote / Global',
  },

  navigation: [
    { label: 'Hero', href: '#hero' },
    { label: 'About', href: '#about' },
    { label: 'Projects', href: '#projects' },
    { label: 'Skills', href: '#skills' },
    { label: 'Contact', href: '#contact' },
  ],

  marqueeItems: [
    'Full Stack Engineering',
    'Computer Science & Algorithms',
    'GSAP Motion & Scroll',
    'Modern React & Node.js',
    'System Architecture',
    'Interactive Web Experiences',
    'Database Design',
    'High-Performance UI',
  ],

  about: {
    lead: 'Computer Science student and full stack developer building robust web applications and expressive digital experiences.',
    bio: [
      'I bridge computer science foundations with modern full-stack engineering. My work focuses on scalable backends, clean API architectures, and highly responsive, motion-driven user interfaces.',
      'From designing relational database schemas and algorithmic optimizations to creating buttery-smooth scroll interactions with GSAP, I care deeply about writing maintainable code that performs at scale.',
    ],
    quote: '"Clean architecture in the backend, purposeful motion on the surface."',
    quoteAuthor: 'Masood Haider // Philosophy',
  },

  journey: [
    {
      id: 'uni-peshawar',
      type: 'University Education',
      badge: 'BS Computer Science',
      title: 'University of Peshawar',
      subtitle: 'Department of Computer Science',
      period: '2022 — 2026',
      status: 'Current Studies',
      description: 'Pursuing Bachelor of Science in Computer Science with a strong emphasis on core data structures, algorithms, operating systems, database management systems, and distributed web architectures.',
      highlight: 'Core Focus: Algorithmic Efficiency, Object-Oriented Systems, and Full-Stack Engineering',
      tags: ['Computer Science', 'Data Structures & Algorithms', 'Operating Systems', 'Database Systems', 'Software Engineering'],
      accentColor: 'var(--accent-primary)',
      cardNumber: '01',
    },
    {
      id: 'uswa-college',
      type: 'Pre-Engineering & High School',
      badge: 'Higher Secondary & High School',
      title: 'Uswa College Islamabad',
      subtitle: 'Pre-Engineering & Science Track',
      period: '2015 — 2021',
      status: 'Graduated',
      description: 'Completed comprehensive secondary and higher secondary education with a focus on Mathematics, Physics, and foundational computing. Built deep analytical problem-solving skills and mathematical discipline.',
      highlight: 'Core Focus: Advanced Mathematics, Physics, and Analytical Logic',
      tags: ['Pre-Engineering', 'Advanced Mathematics', 'Physics', 'Analytical Problem Solving', 'Logic & Foundations'],
      accentColor: 'var(--accent-primary-hover)',
      cardNumber: '02',
    },
    {
      id: 'fullstack-specialization',
      type: 'Technical Specialization',
      badge: 'Full Stack & Motion UI',
      title: 'Production Engineering & Craft',
      subtitle: 'Independent Projects & Systems Architecture',
      period: '2021 — Present',
      status: 'Continuous Mastery',
      description: 'Architecting resilient full-stack platforms, scalable REST/GraphQL APIs, relational database schemas, and crafting fluid 60 FPS GSAP motion interactions and 3D graphics.',
      highlight: 'Core Focus: Resilient Backend Platforms, GSAP Micro-Interactions, and Modern UI Performance',
      tags: ['React & Next.js', 'Node.js & Express', 'GSAP ScrollTrigger', 'PostgreSQL', 'Three.js & WebGL'],
      accentColor: '#C9A876',
      cardNumber: '03',
    },
  ],

  stats: [
    { number: '3', suffix: '+', label: 'Years Coding' },
    { number: '25', suffix: '+', label: 'Projects Built' },
    { number: '100', suffix: '%', label: 'Clean Code Focus' },
    { number: '60', suffix: 'fps', label: 'Motion Target' },
  ],

  projectFilters: [
    { label: 'All Projects', slug: 'all' },
    { label: 'Full Stack', slug: 'fullstack' },
    { label: 'Systems & CS', slug: 'systems' },
    { label: 'Creative Motion', slug: 'motion' },
  ],

  projects: [
    {
      id: 'nexus-stack',
      title: 'Nexus Full Stack Platform',
      category: 'Full Stack & Cloud',
      categorySlug: 'fullstack',
      year: '2026',
      description: 'A distributed web platform with real-time collaboration, microservices architecture, and WebSocket data streams.',
      tags: ['Node.js', 'React', 'PostgreSQL', 'WebSockets', 'GSAP'],
      gradient: 'var(--grad-1)',
      shapeClass: 'shape-nexus',
      liveUrl: '#',
      githubUrl: '#',
    },
    {
      id: 'algo-visualizer',
      title: 'Algorithmic Motion Lab',
      category: 'Computer Science & Visuals',
      categorySlug: 'systems',
      year: '2025',
      description: 'An interactive algorithm visualizer demonstrating graph traversals, dynamic programming, and tree balancing with smooth state transitions.',
      tags: ['Vanilla JS', 'Data Structures', 'GSAP', 'Canvas 2D'],
      gradient: 'var(--grad-2)',
      shapeClass: 'shape-algo',
      liveUrl: '#',
      githubUrl: '#',
    },
    {
      id: 'hyper-commerce',
      title: 'Hyper E-Commerce Engine',
      category: 'Full Stack Application',
      categorySlug: 'fullstack',
      year: '2025',
      description: 'High-speed headless e-commerce store with serverless backend, optimized cart state management, and fluid checkout animations.',
      tags: ['TypeScript', 'Express', 'MongoDB', 'Stripe API', 'Tailwind'],
      gradient: 'var(--grad-3)',
      shapeClass: 'shape-hyper',
      liveUrl: '#',
      githubUrl: '#',
    },
    {
      id: 'zenith-dashboard',
      title: 'Zenith Developer Analytics',
      category: 'Interface & Motion',
      categorySlug: 'motion',
      year: '2024',
      description: 'A dark-mode telemetry dashboard for monitoring API performance, database health, and server memory footprints.',
      tags: ['ScrollTrigger', 'ScrollSmoother', 'Chart.js', 'REST API'],
      gradient: 'var(--grad-4)',
      shapeClass: 'shape-zenith',
      liveUrl: '#',
      githubUrl: '#',
    },
    {
      id: 'lumina-gateway',
      title: 'Lumina Distributed Gateway',
      category: 'System Architecture',
      categorySlug: 'systems',
      year: '2025',
      description: 'High-throughput reverse proxy and caching layer with rate limiting and automated load balancing across microservices.',
      tags: ['Node.js', 'Redis', 'Docker', 'Systems Architecture'],
      gradient: 'var(--grad-2)',
      shapeClass: 'shape-lumina',
      liveUrl: '#',
      githubUrl: '#',
    },
    {
      id: 'vortex-motion',
      title: 'Vortex WebGL Interactive',
      category: 'Creative Motion',
      categorySlug: 'motion',
      year: '2024',
      description: 'Experimental interactive 3D particle system and shader simulation reacting dynamically to scroll and cursor velocity.',
      tags: ['Three.js', 'GSAP Flip', 'GLSL Shaders', 'Web Audio'],
      gradient: 'var(--grad-1)',
      shapeClass: 'shape-vortex',
      liveUrl: '#',
      githubUrl: '#',
    },
  ],

  skills: [
    {
      id: 'fullstack-web',
      category: 'Full Stack & Web Dev',
      badge: '01 // Frontend & Backend Architecture',
      icon: 'code',
      proficiency: 96,
      proficiencyLabel: '96% Production Mastery',
      lead: 'Designing responsive client applications paired with resilient, scalable backend services.',
      metrics: [
        { label: 'Latency Target', value: '<50ms' },
        { label: 'API Protocols', value: 'REST & GraphQL' },
        { label: 'UI Frame Rate', value: '60 FPS' },
      ],
      groups: [
        {
          groupName: 'Frontend Systems',
          items: ['React', 'Next.js', 'TypeScript', 'JavaScript (ES6+)', 'HTML5 & Modern CSS'],
        },
        {
          groupName: 'Backend & Data',
          items: ['Node.js', 'Express', 'PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'WebSockets'],
        },
      ],
    },
    {
      id: 'cs-core',
      category: 'Computer Science Core',
      badge: '02 // Academic & Algorithmic Foundations',
      icon: 'cpu',
      proficiency: 92,
      proficiencyLabel: '92% Academic & Problem Solving',
      lead: 'Strong theoretical grounding in data structures, computational complexity, and system design.',
      metrics: [
        { label: 'Complexity', value: 'O(1) & O(log N)' },
        { label: 'Architecture', value: 'Clean & SOLID' },
        { label: 'Foundations', value: 'BS CS 2026' },
      ],
      groups: [
        {
          groupName: 'Core Disciplines',
          items: ['Data Structures & Algorithms', 'Time & Space Complexity', 'OOP & Design Patterns'],
        },
        {
          groupName: 'Systems Knowledge',
          items: ['Database Normalization', 'Operating Systems', 'Computer Networks', 'System Design'],
        },
      ],
    },
    {
      id: 'motion-ui',
      category: 'Motion & Interactive UI',
      badge: '03 // High-Fidelity Creative Motion',
      icon: 'sparkles',
      proficiency: 95,
      proficiencyLabel: '95% Animation Architecture',
      lead: 'Building expressive, GPU-accelerated web animations and fluid scroll interactions.',
      metrics: [
        { label: 'Rendering Target', value: '60+ FPS' },
        { label: 'Engine', value: 'GSAP Suite' },
        { label: 'Graphics', value: 'WebGL & Canvas' },
      ],
      groups: [
        {
          groupName: 'Animation Suite',
          items: ['GSAP Core', 'ScrollTrigger & Pinning', 'ScrollSmoother', 'SplitText', 'GSAP Flip'],
        },
        {
          groupName: 'Creative Tech',
          items: ['Canvas 2D & SVG', 'WebGL & Three.js Basics', 'Interactive Micro-UI', 'State Morphing'],
        },
      ],
    },
    {
      id: 'tools-devops',
      category: 'Tools, DevOps & Cloud',
      badge: '04 // Modern Engineering Toolchain',
      icon: 'gauge',
      proficiency: 88,
      proficiencyLabel: '88% Engineering Workflow',
      lead: 'Streamlined development environments, containerized deployments, and robust testing.',
      metrics: [
        { label: 'Version Control', value: 'Git & GitHub' },
        { label: 'Containers', value: 'Docker' },
        { label: 'Tooling', value: 'Vite & Webpack' },
      ],
      groups: [
        {
          groupName: 'DevOps & Containers',
          items: ['Docker Basics', 'Linux / Bash Scripting', 'CI/CD Pipelines', 'Environment Configs'],
        },
        {
          groupName: 'Testing & Workflows',
          items: ['Postman & API Testing', 'Vite', 'Webpack', 'VS Code Debugging', 'Agile / Scrum'],
        },
      ],
    },
    {
      id: 'engineering-pillars',
      category: 'Engineering Philosophy',
      badge: '05 // Craft & Technical Standards',
      icon: 'shield',
      proficiency: 100,
      proficiencyLabel: '100% Quality Commitment',
      lead: 'Guiding principles that govern code quality, scalability, maintainability, and user experience.',
      metrics: [
        { label: 'Code Quality', value: 'Self-Documenting' },
        { label: 'Performance', value: 'Lighthouse 95+' },
        { label: 'Reliability', value: 'Defensive Design' },
      ],
      groups: [
        {
          groupName: 'Core Principles',
          items: ['Defensive Architecture', 'Maintainable & Scalable Code', 'Accessibility & Semantic HTML'],
        },
        {
          groupName: 'Execution Craft',
          items: ['Mobile-First Responsiveness', '60 FPS GPU Compositing', 'Continuous Learning & Growth'],
        },
      ],
    },
  ],

  socials: [
    { name: 'GitHub', href: 'https://github.com', icon: 'github' },
    { name: 'LinkedIn', href: 'https://linkedin.com', icon: 'linkedin' },
    { name: 'Twitter / X', href: 'https://twitter.com', icon: 'twitter' },
    { name: 'Email', href: 'mailto:masoodhaider.dev@gmail.com', icon: 'mail' },
  ],
};
